#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

## HELPER FUNCTIONS

# cli logger
logger () {
    if [ -x "$(command -v boxes)" ] && [ -x "$(command -v lolcat)" ];then
        echo $1 | boxes | lolcat
    fi # if [ -x "$(command -v lolcat)" ];then #   msg="`$1`" | lolcat
    # fi
    echo $msg
}


# run function to check for existing instances and avoid duplicates
run() {
    # first check if the command is installed
	  if ! command -v "$1" > /dev/null; then
        echo "The command $1 wanst found in this system."
    fi
    # then check if there isnt already a process with the same name running
    if ! pidof -x $1 ; then # could also use pgrep instead of pidof -x
        echo "Running $1"
        $@&
    else
        echo "$1 is already running"
    fi
}

#java fix

wmname LG3D


## MONITORS CONFIG
monitor1 = "DP-2"
monitor2 = "HDMI-1"
xrandr --output DP-2 --primary -mode 1920x1080 --rotate normal --output HDMI-1 --mode 1680x1050 --rotate normal \ --output DP-0 --off \
--output DP-1 --off \
--output HDMI-0 --off \
--output DP-3 --off \
--output DP-4 --off \
--output DP-5 --off
if [[ "$1" = 0 ]]; then	if [[ $(xrandr -q | grep "${monitor2} connected") ]]; then
		bspc monitor DP-2 -d I II III IV V
		bspc monitor HDMI-1 -d VI VII VIII IX X
		bspc wm -O $monitor1 $monitor2
	else
		bspc monitor $monitor1 -d 1 2 3 4 5 6 7 8 9 10
	fi
fi
##BSPWM CONFIG

bspc config border_width         2
bspc config window_gap          12

# --------------------
# PADDING
bspc config top_padding          24
bspc config bottom_padding       15
bspc config left_padding         0
bspc config right_padding        0

# --------------------
# LAYOUTS
bspc config split_ratio          0.50

# MONOCLE LAYOUT (WHERE EACH WINDOW IS 100% OF THE SCREEN)
bspc config single_monocle       true
bspc config gapless_monocle      false # equivalent of i3 smart gaps, which only applies gaps if theres more than 1 window
bspc config borderless_monocle   false # border for when there is only 1 window (monocle)

# --------------------
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true


#Ability to use mouse to move stuff

bspc config pointer_modifier mod4

bspc config pointer_action1 move 

bspc config pointer_action2 resize_side

bspc config pointer_action2 resize_corner 




#################################################################
# Floating applications
#################################################################

run ~/.config/bspwm/scripts/add-border-to-floating-windows.sh &


#Desktop RULES

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop='^0'
bspc rule -a jetbrains-pycharm desktop='^5'
bspc rule -a Pavucontrol desktop='^0'
bspc rule -a discord desktop='^6'
bspc rule -a TelegramDesktop desktop='^6'
bspc rule -a steam desktop='^7'
bspc rule -a Lutris desktop='^7'
bspc rule -a KeePassXC desktop='^6'

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

# ----------------

#
# Autostart
#

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
.config/bspwm/scripts/launch_polybar.sh & 
# Notifications
/usr/bin/dunst &

# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
# picom -b &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
#~/.config/bspwm/scripts/low_bat_notifier.sh

